CREATE TABLE rsallo_data (long DOUBLE,
                          lat DOUBLE,
                          date DATE,
                          age INTEGER,
                          race VARCHAR(1),
                          sex VARCHAR(1),
                          time VARCHAR(4),
                          cause VARCHAR(16),
                          weapon VARCHAR(16),
                          motive VARCHAR(16),
                          zipcode VARCHAR(16));
